version: '2'

services:
  runner:
    build: . # Caso queira personalizar o Dockerfile.
    # image: gfviegas/cdd # Se usar a opção build, comente esta.
    container_name: ccf-493
    working_dir: /code
    volumes:
      - ./:/code
    ports:
      - 8888:8888
